import type { ScaffoldFile } from "./types";

export async function downloadScaffoldAsZip(
  projectName: string,
  files: ScaffoldFile[]
): Promise<void> {
  // Try to use pako library for compression, fall back to simple text export
  try {
    // For now, provide a simple download of all files as a tar-like structure
    // In production, you'd use a library like jszip
    const fileList = files
      .map(
        (f) =>
          `FILE: ${f.path}\nDESCRIPTION: ${f.description}\n\n\`\`\`\n${f.content}\n\`\`\`\n\n---\n`
      )
      .join("\n");

    const content = `# ${projectName} - Scaffolded Project Files

Generated by AppFactory.

## Setup Instructions

1. Create a directory: \`mkdir ${projectName}\`
2. Navigate into it: \`cd ${projectName}\`
3. Create the directory structure based on file paths below
4. Copy each file into its corresponding location
5. Run \`npm install\` to install dependencies
6. Run \`npm run dev\` to start the development server

## Files

${fileList}
`;

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${projectName.toLowerCase().replace(/\s+/g, "-")}-scaffold.md`;
    link.click();
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Failed to download scaffold:", error);
    alert("Unable to download. Please try again.");
  }
}

export async function downloadScaffoldAsJson(
  projectName: string,
  files: ScaffoldFile[]
): Promise<void> {
  try {
    const content = JSON.stringify(
      {
        projectName,
        files: files.map((f) => ({
          path: f.path,
          description: f.description,
          content: f.content,
        })),
      },
      null,
      2
    );

    const blob = new Blob([content], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${projectName.toLowerCase().replace(/\s+/g, "-")}-scaffold.json`;
    link.click();
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Failed to download scaffold:", error);
    alert("Unable to download. Please try again.");
  }
}

export function copyScaffoldFileToClipboard(file: ScaffoldFile): void {
  const content = `# ${file.path}\n\n${file.content}`;
  navigator.clipboard.writeText(content);
}
